### ISSUE TITLE
Broken debian package for stable: "bullseye"

### ISSUE THREAD

**Issue by paulmillar** [richardlehane/siegfried#222]
When trying to upgrade to siegfried v1.0.0-1, I'm seeing the following error:

```console
paul@celebrimbor:~$ sudo apt-get upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  siegfried
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/20.9 MB of archives.
After this operation, 913 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
dpkg-deb: error: archive '/var/cache/apt/archives/siegfried_1.10.0-1_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up
Traceback (most recent call last):
  File "/usr/share/apt-listchanges/DebianFiles.py", line 124, in readdeb
    output = subprocess.check_output(command)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dpkg-deb', '-f', '/var/cache/apt/archives/siegfried_1.10.0-1_amd64.deb', 'Package', 'Source', 'Version', 'Architecture', 'Status']' returned non-zero exit status 2.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/apt-listchanges", line 323, in <module>
    main(config)
  File "/usr/bin/apt-listchanges", line 104, in main
    pkg = DebianFiles.Package(deb)
  File "/usr/share/apt-listchanges/DebianFiles.py", line 358, in __init__
    parser.readdeb(self.path)
  File "/usr/share/apt-listchanges/DebianFiles.py", line 127, in readdeb
    raise RuntimeError(_("Error processing '%(what)s': %(errmsg)s") %
RuntimeError: Error processing '/var/cache/apt/archives/siegfried_1.10.0-1_amd64.deb': Command '['dpkg-deb', '-f', '/var/cache/apt/archives/siegfried_1.10.0-1_amd64.deb', 'Package', 'Source', 'Version', 'Architecture', 'Status']' returned non-zero exit status 2.
dpkg-deb: error: archive '/var/cache/apt/archives/siegfried_1.10.0-1_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive /var/cache/apt/archives/siegfried_1.10.0-1_amd64.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /var/cache/apt/archives/siegfried_1.10.0-1_amd64.deb
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
paul@celebrimbor:~$ 
```
Here is what seems to be [a related issue](https://unix.stackexchange.com/questions/669004/zst-compression-not-supported-by-apt-dpkg) on stack exchange.

In the stack exchange discussion, their problem is identified as the package being built with a newer version of dpkg (>= 1.21.18), which [includes support](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892664) this new compression.

I can confirm that my version of dpkg is older, so doesn't support this compression.

```console
paul@celebrimbor:~$ dpkg-query -W dpkg
dpkg    1.20.12
paul@celebrimbor:~$ 
```

Moreover, I'm running the current stable version of Debian, "bullseye":

```console
paul@celebrimbor:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
paul@celebrimbor:~$ 
```

**Comment by richardlehane** [comment]
thanks for this detailed report Paul, I'll look into it
